basePath: /api/v1/
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3111
info:
  contact:
    email: philixbob@gmail.com
    name: Felix Eligbue
    url: http://www.swagger.io/support
  description: Harmony Backend Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Harmony
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
